### ISSUE TITLE
How can I assign this to a variable?

### ISSUE THREAD

**Issue by marcuxyz** [cnguy/kayn#16]
How can I assign this to a variable?

e.g:
`let summoner = k.Summoner.get({ name }, KindredAPI.print)`

Thanks

**Comment by cnguy** [comment]
Hi there!

This isn't an issue with the library itself. This is the nature of asynchronous programming in Node.js.

What you need to do instead is pass a callback to the second parameter like so
```javascript
// using callbacks
k.Summoner.get({ name }, function (err, data) {
  // do stuffs here asynchronously
});

// or using promises in ES6
k.Summoner
 .get({ name })
 .then((data) => {
   // do stuffs here asynchronously
 })
 .catch((err) => {
    console.error(err)
 });
```
and do whatever you need in the callback.

I suggest you read a lot about callbacks to get the hang of it.

Basically, you can't just store calls like these because the request can finish anytime in the future. The standard way of doing this instead is to pass in a function that gets called the moment this request is completed (which means there is either an error or a successful response which means you got data). These are callbacks.

The standard callback is a function that takes two parameters: error, and data. To do anything with Node.js libraries, you're most likely just going to pass callbacks (or use ES6 promises or ES7 await/async).

https://stackoverflow.com/questions/29594731/nodejs-saving-json-to-a-variable
https://stackoverflow.com/questions/23667086/why-is-my-variable-unaltered-after-i-modify-it-inside-of-a-function-asynchron
