### ISSUE TITLE
Ability to specify query parameters for matchlist

### ISSUE THREAD

**Issue by aj-r** [cnguy/kayn#41]
For the [matchlist endpoint](https://developer.riotgames.com/api-methods/#match-v3/GET_getMatchlist), it is critical to be able to pass query parameters (`beginTime`, `beginIndex`, etc.) - without those parameters, its use case is very limited.

Or is there a way to do this that I'm missing?

**Comment by cnguy** [comment]
@aj-r 

docs: https://github.com/cnguy/kayn#adding-query-parameters-to-a-request

example in my own project: https://github.com/cnguy/OneTricks/blob/master/stats/StatsGenerator.js#L133

Hello! Yes, you can pass query parameters via the `query` method.

You can chain multiple `query`'s like:

```javascript
kayn.Matchlist.by.summonerID(123456).query({ beginIndex: 0 }).query({ endIndex: 50 })
```

or just pass in the entire object:

```javascript
kayn.Matchlist.by.summonerID(123456).query({ beginIndex: 0, endIndex: 50 })
```

Is this what you're looking for?

All requests can be passed the `region` and/or `query` methods.

To verify that your query parameters are being passed, make sure debugging is set on so that you can see the URL being produced by the method.

**Comment by aj-r** [comment]
Oh awesome, that's exactly what I was looking for. Thanks!
