### ISSUE TITLE
Function Matchlist.by.accountID don't support the other parameters

### ISSUE THREAD

**Issue by rafaeelaudibert** [cnguy/kayn#47]
Using the function kayn.Matchlist.by.accountID(accountId), I can't use the other parameters that I can use with the API, like specifying Season e/or Champion

**Comment by cnguy** [comment]
Hi!

`kayn` is different from the other libraries in that the `region` and `query` parameters are passed via chainable functions. This is good for me and the library because it heavily reduces duplicate implementation code.

```javascript
kayn.Matchlist.by.accountID(3440481)
    .region(REGIONS.KOREA)
    .query({
        champion: 67,
        season: 9,
    })
    .callback(function(err, matchlist) {
        console.log(matchlist.matches.length)
    })
```

Basically, for every `kayn` method, you can chain a `region` or `query` function. To then pass a callback, you chain it with the `callback` function.

To use promises, you simply just call the `then` function without the `callback` function.

```javascript
kayn.Matchlist.by.accountID(accountId)
    .region(etc)
    .query(etc)
    .then(data => console.log(data))
    .catch(error => console.error(error))
```

To async/await, you simply call the function without any callback/then chaining:

```javascript
const matchlist = await kayn.Matchlist.by.accountID(accountId).region(etc).query(etc)
```

Look at the `./examples` directory for more detailed code.

**Comment by rafaeelaudibert** [comment]
Okay thanks, I dind't find that examples with the query, really aprecciated it 😄 
Keep doing your great job
